-- Supabase Database Schema for Edunai (PostgreSQL)

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. PROFILES & AUTHENTICATION
-- ==========================================
-- This table automatically links with Supabase's auth.users
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  university TEXT,
  major TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Turn on RLS for profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all profile names." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update their own profile." ON profiles FOR UPDATE USING (auth.uid() = id);


-- ==========================================
-- 2. FEATURE 1: PLANNING KEGIATAN (Smart Scheduler)
-- ==========================================
-- Calendar events and daily tasks
CREATE TABLE events (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  is_all_day BOOLEAN DEFAULT FALSE,
  color TEXT DEFAULT 'blue',
  event_type TEXT DEFAULT 'class', -- e.g., 'class', 'exam', 'meeting', 'task'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own events" ON events FOR ALL USING (auth.uid() = user_id);


-- ==========================================
-- 3. FEATURE 3: COLLABORATIVE PROJECT BOARDS
-- ==========================================
-- The main Workspace/Boards
CREATE TABLE boards (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  cover_image TEXT,
  join_code TEXT UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Board Members (Many-to-Many for collaboration)
CREATE TABLE board_members (
  board_id UUID REFERENCES public.boards(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  role TEXT DEFAULT 'editor', -- 'admin', 'editor', 'viewer'
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  PRIMARY KEY (board_id, user_id)
);

-- Board Lists (Columns: To Do, In Progress, Done)
CREATE TABLE board_lists (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  board_id UUID REFERENCES public.boards(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  position INTEGER NOT NULL, -- To sort columns horizontally
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Board Cards (The actual tasks inside lists)
CREATE TABLE board_cards (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  list_id UUID REFERENCES public.board_lists(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  due_date TIMESTAMP WITH TIME ZONE,
  position INTEGER NOT NULL, -- To sort cards vertically
  labels JSONB DEFAULT '[]'::jsonb, -- Array of colored tags
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Notes on Board RLS:
-- We allow access to Boards if auth.uid() is the owner OR exists in board_members table.


-- ==========================================
-- 4. FEATURE 2 & 4: ADVANCED NOTES & AI BOARD SCANNER
-- ==========================================
CREATE TABLE notes (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  content_markdown TEXT, -- Stores the rich text / markdown content
  original_image_url TEXT, -- Used if the note was generated via AI Vision OCR
  tags TEXT[] DEFAULT '{}',
  is_favorite BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own notes" ON notes FOR ALL USING (auth.uid() = user_id);


-- ==========================================
-- 5. FEATURE 5: AI STUDY ASSISTANT (Flashcards/Quizzes)
-- ==========================================
-- Flashcard Collections generated by AI
CREATE TABLE study_sets (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  note_id UUID REFERENCES public.notes(id) ON DELETE SET NULL, -- Which note birthed this set (Optional)
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Individual Flashcards
CREATE TABLE flashcards (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  set_id UUID REFERENCES public.study_sets(id) ON DELETE CASCADE NOT NULL,
  front_text TEXT NOT NULL,
  back_text TEXT NOT NULL,
  mastery_level INTEGER DEFAULT 0, -- Ranging 0 - 5 for spacing repetition algorithms
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE study_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE flashcards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their study sets" ON study_sets FOR ALL USING (auth.uid() = user_id);
-- Flashcards RLS can join through study_sets to check ownership

-- ==========================================
-- 6. TRIGGERS & FUNCTIONS
-- ==========================================
-- Automatic profile creation when a new user signs up via Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id,
    -- Google OAuth uses 'name', email/password signup uses 'full_name'
    COALESCE(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      split_part(new.email, '@', 1)
    ),
    COALESCE(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture'
    )
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = COALESCE(
      EXCLUDED.full_name,
      profiles.full_name
    ),
    avatar_url = COALESCE(
      EXCLUDED.avatar_url,
      profiles.avatar_url
    );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ==========================================
-- 7. UX FEATURES: ONBOARDING, ACTIVITY & RESUME
-- ==========================================

-- Feature 1: Onboarding fields on profiles
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS study_goal TEXT,    -- 'exam' | 'hobby' | 'career'
  ADD COLUMN IF NOT EXISTS skill_level TEXT;   -- 'beginner' | 'intermediate' | 'advanced'

-- Feature 4: Resume Card — last tool visited
CREATE TABLE IF NOT EXISTS user_activity (
  user_id          UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  last_tool        TEXT,         -- 'notes', 'flashcards', 'boards', 'schedule', 'scanner'
  last_resource_id UUID,         -- ID of the last item the user opened
  last_resource_title TEXT,
  progress_value   INTEGER DEFAULT 0,  -- 0–100
  last_visited_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE user_activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own activity" ON user_activity
  FOR ALL USING (auth.uid() = user_id);

-- Feature 5: Activity Heatmap log
CREATE TABLE IF NOT EXISTS activity_log (
  id             UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id        UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  activity_date  DATE DEFAULT CURRENT_DATE,
  activity_count INTEGER DEFAULT 1,
  UNIQUE(user_id, activity_date)
);

ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own activity log" ON activity_log
  FOR ALL USING (auth.uid() = user_id);

-- ==========================================
-- 8. FEATURE 6: STUDY GROUPS & CHAT
-- ==========================================
CREATE TABLE study_groups (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  group_type TEXT DEFAULT 'private', -- 'public' or 'private'
  join_code TEXT UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE study_group_members (
  group_id UUID REFERENCES public.study_groups(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  role TEXT DEFAULT 'member', -- 'admin', 'member'
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  PRIMARY KEY (group_id, user_id)
);

CREATE TABLE study_group_messages (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  group_id UUID REFERENCES public.study_groups    (id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT,
  attachment_type TEXT, -- 'note', 'board', null
  attachment_id UUID,   -- ID of the note or board
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE study_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_group_messages ENABLE ROW LEVEL SECURITY;

-- Policies for study_groups
CREATE POLICY "Users can create study groups" ON study_groups FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Users can view all study groups" ON study_groups FOR SELECT USING (true);
CREATE POLICY "Owner can update study groups" ON study_groups FOR UPDATE USING (auth.uid() = owner_id);
CREATE POLICY "Owner can delete study groups" ON study_groups FOR DELETE USING (auth.uid() = owner_id);

-- Policies for study_group_members
CREATE POLICY "Users can join study groups" ON study_group_members FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view members" ON study_group_members FOR SELECT USING (true);
CREATE POLICY "Users can leave or update members" ON study_group_members FOR ALL USING (auth.uid() = user_id);

-- Policies for study_group_messages
CREATE POLICY "Users can send messages" ON study_group_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view messages" ON study_group_messages FOR SELECT USING (true);

-- ==========================================
-- MIGRATIONS / UPDATES
-- ==========================================
-- Menambahkan kolom subject untuk Live Sessions
ALTER TABLE study_groups ADD COLUMN IF NOT EXISTS subject TEXT;

-- Policies for study_group_members
CREATE POLICY "Users can join study groups" ON study_group_members FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view members" ON study_group_members FOR SELECT USING (true);
CREATE POLICY "Users can leave or update members" ON study_group_members FOR ALL USING (auth.uid() = user_id);

-- Policies for study_group_messages
CREATE POLICY "Users can send messages" ON study_group_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view messages" ON study_group_messages FOR SELECT USING (true);

-- Allow viewing notes shared in study groups (read-only for all authenticated users)
-- The existing policy "Users can manage their own notes" covers INSERT/UPDATE/DELETE for owners.
-- This new policy allows any authenticated user to SELECT (view) notes.
CREATE POLICY "Authenticated users can view shared notes"
  ON notes FOR SELECT
  USING (auth.role() = 'authenticated');
